fix(react-output-target): assign ExpandedPropTypes to reducer (#306)
cast the `ExpandedPropTypes` to the initial value of the reducer to prevent an error at build time:
> error TS2322: Type 'ExpandedPropsTypes' is not assignable to type '{}'

this would occur due to the initial value of the reducer function being `{}` and is not assignable to the `ExpandedPropTypes` type.